  #设置端口
server:
  port: 80

spring:
  thymeleaf:
    # 关闭页面缓存
    cache: false
    # 配置数据源
  datasource:
    url: jdbc:mysql:///school_db?serverTimezone=GMT%2B8
    username: root
    password: zhang
    driver-class-name: com.mysql.cj.jdbc.Driver
  #扫描映射文件路径
mybatis-plus:
  mapper-locations:
